server:
  port: ${PORT:8792}
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: ordering-service
          uri: lb://ORDERING-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ordering-service
                fallbackuri: forward:/orderingFallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallback
        - id: organisation-mgmt-service
          uri: lb://ORGANISATION-MANAGEMENT-SERVICE
          predicates:
            - Path=/organisation/**
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

microservice:
  payment-service:
    endpoints:
      make-payment:
        uri: http://PAY
  ordering-service:
    endpoints:
      make-order:
        uri: http://PAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost