server:
  port: ${PORT:8792}
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: ordering-service
          uri: lb://ORDERING-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://order-mgmt-service-registry.herokuapp.com/eureka/
  instance:
    hostname: localhost